  $(document).ready(
        function(){
                $("#register").click(function(){
                        window.location.href="register.html"
                });
                $("#login").click(function(){
                        window.location.href="login.html"
                });
        });